language: node_js
sudo: false
node_js:
  - "stable"
install: 
  - npm install
script:
  - npm test
cache:
  directories:
   - "node_modules"
after_success:
  - npm run coveralls
branches:
  only:
    - develop
    - ch-write-tests-with-ci-152327803
notifications:
  webhooks:
    - https://coveralls.io/webhook
  repo_token: 
    - tAMEScbV1s2SAEiDg0odGKPCSufKKzzbo